name: ci

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
  workflow_run:
    workflows: [kernel-kit]
    branches: [testing]
    types:
      - completed

jobs:
  build:
    if: (github.event_name != 'schedule') || (github.event_name == 'schedule' && github.repository == 'puppylinux-woof-CE/woof-CE' && github.ref == 'refs/heads/testing') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.unionfs == 'aufs' }}
    strategy:
      matrix:
        include:
          - arch: x86
            compat-distro: slackware
            compat-distro-version: 14.2
            kernel: 4.19.x-x86
            unionfs: aufs
          - arch: x86
            compat-distro: debian
            compat-distro-version: bullseye
            kernel: debian-bullseye-x86
            unionfs: overlay
          - arch: x86
            compat-distro: debian
            compat-distro-version: bookworm
            kernel: debian-bookworm-x86
            unionfs: overlay
          - arch: x86_64
            compat-distro: slackware64
            compat-distro-version: 14.2
            kernel: 4.19.x-x86_64
            unionfs: aufs
          - arch: x86_64
            compat-distro: debian
            compat-distro-version: bullseye64
            kernel: debian-bullseye-x86_64
            unionfs: overlay
          - arch: x86_64
            compat-distro: debian
            compat-distro-version: bookworm64
            kernel: debian-bookworm-x86_64
            unionfs: overlay
          - arch: x86_64
            compat-distro: ubuntu
            compat-distro-version: jammy64
            kernel: 5.15.x-x86_64
            unionfs: aufs
          - arch: x86_64
            compat-distro: ubuntu
            compat-distro-version: focal64
            kernel: 5.10.x-x86_64
            unionfs: aufs
          - arch: x86_64
            compat-distro: slackware64
            compat-distro-version: "15.0"
            kernel: 5.15.x-x86_64
            unionfs: aufs
          - arch: x86
            compat-distro: slackware
            compat-distro-version: "15.0"
            kernel: 5.15.x-x86
            unionfs: aufs
          - arch: x86_64
            compat-distro: ubuntu
            compat-distro-version: bionic64
            kernel: 4.19.x-x86_64
            unionfs: aufs
          - arch: x86_64
            compat-distro: debian
            compat-distro-version: sid64
            kernel: debian-sid-x86_64
            unionfs: overlay
    steps:
    - uses: ./.github/workflows/build.yml
      with:
        name: ${{ matrix.name }}
        arch: ${{ matrix.arch }}
        compat_distro: ${{ matrix.compat-distro }}
        compat_version: ${{ matrix.compat-distro-version }}
        kernel: ${{ matrix.kernel }}
        unionfs: ${{ matrix.unionfs }}
        artifact: ${{ github.workflow }}-${{ matrix.arch }}-${{ matrix.compat-distro }}-${{ matrix.compat-distro-version }}-${{ github.run_number }}