name: dpupos

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            kernel-version: 5.4.x
            prefix:
            tag: rolling
          - arch: x86
            kernel-version: 4.19.x
            prefix: linux32
            tag: rolling32
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output
        ln -s `basename $(pwd)`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ matrix.arch }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ matrix.arch }}-local-repositories-
    - name: Prepare build environment
      run: docker run --rm -it --privileged -v /dev:/dev -v `pwd`/..:/tmp/share -e GITHUB_ACTIONS -w /tmp/share/`basename $(pwd)` -d --name builder ghcr.io/dpupos/container/dpupos:${{ matrix.tag }}
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: yes "" | docker exec builder ${{ matrix.prefix }} ./merge2out woof-distro/${{ matrix.arch }}/debian/dpupos
    - name: Set version
      run: sudo sed s/^DISTRO_VERSION=.*/DISTRO_VERSION=2/ -i ../woof-out_*/DISTRO_SPECS
    - name: 0setup
      run: docker exec builder sh -c "cd ../woof-out_* && ${{ matrix.prefix }} ./0setup"
    - name: 1download
      run: docker exec builder sh -c "cd ../woof-out_* && ${{ matrix.prefix }} ./1download"
    - name: 2createpackages
      run: docker exec builder sh -c "cd ../woof-out_* && ${{ matrix.prefix }} ./2createpackages"
    - name: Get cached kernel-kit output
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: dpupos/woof-CE
        branch: testing
        workflow: dpupos-kernel.yml
        workflow_conclusion: success
        name: dpupos-kernel-${{ matrix.kernel-version }}-${{ matrix.arch }}
        path: output
    - name: Move cached kernel-kit output
      run: sudo mv output ../woof-out_*/kernel-kit/
    - name: Get cached petbuild-sources
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Get cached petbuild-cache
      uses: actions/cache@v2
      with:
        path: petbuild-cache
        key: ${{ github.workflow }}-${{ matrix.arch }}-petbuild-cache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ matrix.arch }}-petbuild-cache-
    - name: Get cached petbuild-output
      uses: actions/cache@v2
      with:
        path: petbuild-output
        key: ${{ github.workflow }}-${{ matrix.arch }}-petbuild-output-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ matrix.arch }}-petbuild-output-
    - name: 3builddistro
      run: |
        sudo chown -R root:root petbuild-output
        sudo mv petbuild-{sources,cache,output} ../woof-out_*/
        docker exec builder sh -c "cd ../woof-out_* && HOME=/root ${{ matrix.prefix }} ./3builddistro release"
        docker stop builder
        sudo rm -rf ../woof-out_*/sandbox3
        sudo mv ../woof-out_*/petbuild-{sources,cache,output} .
    - name: Move tarball
      run: sudo mv -f ../woof-out_*/woof-output-*/dpupos-2.tar .
    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}-${{ matrix.arch }}-${{ github.run_number }}
        path: dpupos-2.tar
        retention-days: 3