name: dpupos-rolling

on:
  push:
    branches:
      - dpupos
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:
    branches:
      - dpupos

jobs:
  x86_64:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update package lists
      run: sudo apt-get update -qq
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ github.job }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 3; echo 1; echo 3; echo) | sudo -E ./merge2out
    - name: Set version
      run: sudo sed s/^DISTRO_VERSION=.*/DISTRO_VERSION=1/ -i ../woof-out_x86_64_x86_64_debian_dpupos/DISTRO_SPECS
    - name: Enable updates
      run: sudo sed 's/RELEASE_CHANNEL=.*/RELEASE_CHANNEL=beta/' -i ../woof-out_x86_64_x86_64_debian_dpupos/rootfs-packages/pm6_updater/etc/pm6_updater.conf 
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_x86_64_debian_dpupos
        sudo -E ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_x86_64_debian_dpupos
        sudo -E ./1download
    - name: Install kernel-kit dependencies
      run: |
        sudo apt-get install -y --no-install-recommends ccache libelf-dev libssl-dev
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: kernel-kit
      run: |
        cd ../woof-out_x86_64_x86_64_debian_dpupos/kernel-kit
        sudo cp -f dpupos-build-x86_64.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_x86_64_debian_dpupos
        echo | sudo -E ./2createpackages
    - name: Get cached petbuild-sources
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Install 3builddistro dependencies
      run: |
        sudo apt-get install -y --no-install-recommends vboot-kernel-utils cgpt extlinux
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: 3builddistro
      run: |
        sudo mv petbuild-sources ../woof-out_x86_64_x86_64_debian_dpupos/
        cd ../woof-out_x86_64_x86_64_debian_dpupos
        sudo -E HOME=/root DISTRO_EXTRAVERSION=rolling${{ github.run_number }} ./3builddistro release
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        release_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        body: dpup OS rolling build ${{ github.run_number }} for ${{ github.job }}
        draft: false
        prerelease: true
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_debian_dpupos/woof-output-dpupos-1/dpupos-1.tar
        asset_name: dpupos-1.tar
        asset_content_type: application/octet-stream
    - name: Compress image
      run: sudo gzip -1 ../woof-out_x86_64_x86_64_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb.img
    - name: Compress legacy image
      run: sudo gzip -1 ../woof-out_x86_64_x86_64_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb-legacy.img
    - name: Upload image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb.img.gz
        asset_name: dpupos-1-ext4-2gb.img.gz
        asset_content_type: application/octet-stream
    - name: Upload legacy image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb-legacy.img.gz
        asset_name: dpupos-1-ext4-2gb-legacy.img.gz
        asset_content_type: application/octet-stream
    - name: Upload kernel sources
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_debian_dpupos/kernel-kit/output/kernel_sources-5.4-dpupos.sfs
        asset_name: kernel_sources-5.4-dpupos.sfs
        asset_content_type: application/octet-stream
    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 2
        delete_tag_pattern: dpupos-${{ github.job }}-1-rolling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_64_x86_64_debian_dpupos/petbuild-sources .
  arm-c201:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update package lists
      run: sudo apt-get update -qq
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ github.job }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 1; echo 1; echo; echo) | sudo -E ./merge2out
    - name: Set version
      run: sudo sed s/^DISTRO_VERSION=.*/DISTRO_VERSION=1/ -i ../woof-out_x86_64_arm_debian_dpupos-c201/DISTRO_SPECS
    - name: Enable updates
      run: sudo sed 's/RELEASE_CHANNEL=.*/RELEASE_CHANNEL=beta/' -i ../woof-out_x86_64_arm_debian_dpupos-c201/rootfs-packages/pm6_updater/etc/pm6_updater.conf 
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_arm_debian_dpupos-c201/
        sudo -E ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_arm_debian_dpupos-c201/
        sudo -E ./1download
    - name: Install kernel-kit dependencies
      run: |
        sudo apt-get install -y --no-install-recommends ccache libelf-dev libssl-dev gcc-arm-linux-gnueabihf
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: kernel-kit
      run: |
        cd ../woof-out_x86_64_arm_debian_dpupos-c201/kernel-kit
        sudo cp -f dpupos-build-c201.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_arm_debian_dpupos-c201/
        echo | sudo -E ./2createpackages
    - name: Get cached petbuild-sources
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Install 3builddistro dependencies
      run: |
        sudo apt-get install -y --no-install-recommends vboot-kernel-utils u-boot-tools device-tree-compiler cgpt qemu-user-static binfmt-support
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: 3builddistro
      run: |
        sudo mv petbuild-sources ../woof-out_x86_64_arm_debian_dpupos-c201/
        cd ../woof-out_x86_64_arm_debian_dpupos-c201/
        sudo -E HOME=/root DISTRO_EXTRAVERSION=rolling${{ github.run_number }} ./3builddistro release
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        release_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        body: dpup OS rolling build ${{ github.run_number }} for ${{ github.job }}
        draft: false
        prerelease: true
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_arm_debian_dpupos-c201/woof-output-dpupos-1/dpupos-1.tar
        asset_name: dpupos-1.tar
        asset_content_type: application/octet-stream
    - name: Compress image
      run: sudo gzip -1 ../woof-out_x86_64_arm_debian_dpupos-c201/woof-output-dpupos-1/dpupos-1-ext4-2gb.img
    - name: Upload image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_arm_debian_dpupos-c201/woof-output-dpupos-1/dpupos-1-ext4-2gb.img.gz
        asset_name: dpupos-1-ext4-2gb.img.gz
        asset_content_type: application/octet-stream
    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 2
        delete_tag_pattern: dpupos-${{ github.job }}-1-rolling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_64_arm_debian_dpupos-c201/petbuild-sources .
  x86:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update package lists
      run: sudo apt-get update -qq
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ github.job }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 2; echo 1; echo 3; echo) | sudo -E ./merge2out
    - name: Set version
      run: sudo sed s/^DISTRO_VERSION=.*/DISTRO_VERSION=1/ -i ../woof-out_x86_x86_debian_dpupos/DISTRO_SPECS
    - name: Enable updates
      run: sudo sed 's/RELEASE_CHANNEL=.*/RELEASE_CHANNEL=beta/' -i ../woof-out_x86_x86_debian_dpupos/rootfs-packages/pm6_updater/etc/pm6_updater.conf 
    - name: 0setup
      run: |
        cd ../woof-out_x86_x86_debian_dpupos
        sudo -E linux32 ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_x86_debian_dpupos
        sudo -E linux32 ./1download
    - name: Install kernel-kit dependencies
      run: |
        sudo apt-get install -y --no-install-recommends ccache libelf-dev libssl-dev
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: kernel-kit
      run: |
        cd ../woof-out_x86_x86_debian_dpupos/kernel-kit
        sudo cp -f dpupos-build-x86.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_x86_debian_dpupos
        echo | sudo -E linux32 ./2createpackages
    - name: Get cached petbuild-sources
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Install 3builddistro dependencies
      run: |
        sudo apt-get install -y --no-install-recommends vboot-kernel-utils cgpt extlinux
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: 3builddistro
      run: |
        sudo mv petbuild-sources ../woof-out_x86_x86_debian_dpupos/
        cd ../woof-out_x86_x86_debian_dpupos
        sudo -E HOME=/root DISTRO_EXTRAVERSION=rolling${{ github.run_number }} linux32 ./3builddistro release
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        release_name: dpupos-${{ github.job }}-1-rolling${{ github.run_number }}
        body: dpup OS rolling build ${{ github.run_number }} for ${{ github.job }}
        draft: false
        prerelease: true
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_x86_debian_dpupos/woof-output-dpupos-1/dpupos-1.tar
        asset_name: dpupos-1.tar
        asset_content_type: application/octet-stream
    - name: Compress image
      run: sudo gzip -1 ../woof-out_x86_x86_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb.img
    - name: Compress legacy image
      run: sudo gzip -1 ../woof-out_x86_x86_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb-legacy.img
    - name: Upload image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_x86_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb.img.gz
        asset_name: dpupos-1-ext4-2gb.img.gz
        asset_content_type: application/octet-stream
    - name: Upload legacy image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_x86_debian_dpupos/woof-output-dpupos-1/dpupos-1-ext4-2gb-legacy.img.gz
        asset_name: dpupos-1-ext4-2gb-legacy.img.gz
        asset_content_type: application/octet-stream
    - name: Upload kernel sources
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_x86_debian_dpupos/kernel-kit/output/kernel_sources-4.19-dpupos.sfs
        asset_name: kernel_sources-4.19-dpupos.sfs
        asset_content_type: application/octet-stream
    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 2
        delete_tag_pattern: dpupos-${{ github.job }}-1-rolling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_x86_debian_dpupos/petbuild-sources .