name: slacko64

on:
  push:
    branches:
      - ci
      - testing
    paths:
      - 'woof-distro/x86_64/slackware64/15.0/**'
      - 'woof-code/**'
      - '!woof-code/support/arm_**'
      - 'woof-arch/x86_64/**'
      - 'merge2out'
      - '!**.svg'
      - '!**.png'
      - '!**.htm'
      - '!**.html'
  pull_request:
    branches:
      - testing
    paths:
      - 'woof-distro/x86_64/slackware64/15.0/**'
      - 'kernel-kit/build.sh'
      - 'kernel-kit/slacko64-build.conf'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
    branches:
      - ci
      - testing
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'prepreprealpha1'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-local-repositories-
    - name: Install cdrtools
      run: |
        [ -f local-repositories/mkisofs ] || (curl -L https://sourceforge.net/projects/cdrtools/files/alpha/cdrtools-3.02a09.tar.bz2/download | tar -xjf- && cd cdrtools-3.02 && make -j`nproc` && mv mkisofs/OBJ/x86_64-linux-cc/mkisofs ../local-repositories/mkisofs)
        sudo install -m 755 local-repositories/mkisofs /usr/local/bin/mkisofs
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
        sudo ln -s bash /bin/ash
    - name: merge2out
      run: |
        (echo 3; echo 2; echo 4; echo; echo) | sudo -E ./merge2out
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_15.0
        sudo ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_15.0
        sudo ./1download
    - name: Get cached kernel-kit output
      id: get_kernel_kit_output_cache
      uses: actions/cache@v2
      with:
        path: kernel-kit-output
        key: ${{ github.workflow }}-kernel-kit-output-${{ hashFiles('kernel-kit/**') }}
        restore-keys: |
          ${{ github.workflow }}-kernel-kit-output-
    - name: Move cached kernel-kit output
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit == 'true'
      run: sudo mv kernel-kit-output ../woof-out_x86_64_x86_64_slackware64_15.0/kernel-kit/output
    - name: Install ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y --no-install-recommends ccache
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: Get cached ~/.ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ github.workflow }}-ccache-${{ hashFiles('kernel-kit/**') }}-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-ccache-${{ hashFiles('kernel-kit/**') }}-
    - name: kernel-kit
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_15.0/kernel-kit
        sudo cp -f slacko64-build.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_15.0
        echo | sudo ./2createpackages
    - name: Get cached petbuild-sources
      id: get_petbuild_sources_cache
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Get cached petbuild-cache
      id: get_petbuild_cache
      uses: actions/cache@v2
      with:
        path: petbuild-cache
        key: ${{ github.workflow }}-petbuild-cache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-cache-
    - name: Get cached petbuild-output
      id: get_petbuild_output_cache
      uses: actions/cache@v2
      with:
        path: petbuild-output
        key: ${{ github.workflow }}-petbuild-output-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-output-
    - name: 3builddistro
      run: |
        sudo chown -R root:root petbuild-output
        sudo mv petbuild-{sources,cache,output} ../woof-out_x86_64_x86_64_slackware64_15.0/
        cd ../woof-out_x86_64_x86_64_slackware64_15.0
        sudo -E ./3builddistro
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_64_x86_64_slackware64_15.0/petbuild-{sources,cache,output} .
        sudo mv ../woof-out_x86_64_x86_64_slackware64_15.0/kernel-kit/output kernel-kit-output
    - name: Create Release
      if: github.event_name == 'workflow_dispatch'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: slacko64-8.0-${{ github.event.inputs.release_name }}
        release_name: slacko64-8.0-${{ github.event.inputs.release_name }}
        draft: false
        prerelease: true
    - name: Upload ISO
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_slackware64_15.0/woof-output-slacko64-8.0/slacko64-8.0.iso
        asset_name: slacko64-8.0.iso
        asset_content_type: application/octet-stream
    - name: Upload devx
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_slackware64_15.0/woof-output-slacko64-8.0/devx_slacko64_8.0.sfs
        asset_name: devx_slacko64_8.0.sfs
        asset_content_type: application/octet-stream
